### ISSUE TITLE
Problem with execution simplest function

### ISSUE THREAD

**Issue by serverlesspolska** [activescott/serverless-http-invoker#12]
Hi, I've got a problem with testing of simplest function
```
module.exports.main = (event, context, callback) => {
    const response = {
        statusCode: 200,
        body: JSON.stringify({
            generated: true,
            pdf: 'PDF'
        }),
    };
    callback(null, response)
};
```
serverless.yml
```
service: test

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  profile: ${self:custom.myProfile.${self:custom.myStage}}
  region: ${self:custom.myRegion.${self:custom.myStage}}

custom:
  myStage: ${opt:stage, self:provider.stage}
  myProfile:
    dev: default
    prod: default
  myRegion:
    dev: eu-central-1
    prod: eu-central-1

functions:
  test:
    handler: src/test.main
    name: test
    memorySize: 128
    events:
      - http:
          path: test
          method: get
          cors: true
```
When I manually trigger this function `sls invoke local -f test` I got following result:
```
Serverless: INVOKING INVOKE
{
    "statusCode": 200,
    "body": "{\"generated\":true,\"pdf\":\"PDF\"}"
}
```

However when executing from test
```
const ServerlessInvoker = require('serverless-http-invoker')
const expect = require('chai').expect

describe('PDF Generator tests', () => {
    let sls = new ServerlessInvoker()
    it('should work', function () {
        let response = sls.invoke('GET test')
        response.then( r => {
            console.log(r)
            // return expect(r).to.eventually.have.deep.property('body', {message: 'postit:boo'})
        })
    });
});
```

I get

```

  console.log src/__test__/handler.test.js:25
    { statusCode: 502,
      body:
       { message: 'Internal server error',
         test_debug_error_message: 'Error: Invalid input. Expected either lambda module (with exposed handler) or AWS Lambda configuration (with provided \'lambdaFunction\' name)',
         test_debug_error_stack: 'Error: Invalid input. Expected either lambda module (with exposed handler) or AWS Lambda configuration (with provided \'lambdaFunction\' name)\n    at new Wrapped (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/lambda-wrapper/index.js:17:15)\n    at wrap (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/lambda-wrapper/index.js:105:32)\n    at Promise.try (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/serverless-http-invoker/index.js:149:20)\n    at tryCatcher (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/method.js:39:29)\n    at ServerlessInvoker.invokeWithLambdaWrapper (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/serverless-http-invoker/index.js:147:23)\n    at loadServerlessEnvironment.then (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/serverless-http-invoker/index.js:80:23)\n    at tryCatcher (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async.Object.<anonymous>.Async._drainQueue (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/async.js:138:12)\n    at Async.Object.<anonymous>.Async._drainQueues (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/pawel/serverless/Hireflow/assessmentReport/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)' } }
```

Any idea what is going on?

maybe this "Serverless: INVOKING INVOKE" from sls is a problem?
